# -*- coding: utf-8 -*-
"""Netflix Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWZxQVfIP0dOZi81Uzd9toqM7Q8WPfjB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/mymoviedb.csv',lineterminator = '\n')

df.head()

df.info()

df['Genre'].head()

df.duplicated().sum()

df.describe()

# Exploratry summary

#Findings of data:

#We have a dataframe consisting of 9827 Rows and 9 Columns
#Our dataset looks a bit tidy with no Nans nor duplicate values

#Pre-processing Requirement

#1.Release_date column need to be casted intodate time and to extract only the year value
#2.Overview, Original_Language and Poster_Url wouldn't be so useful during analysis so we will drop these column
#3.Vote_average better be categorized for proper Analysis
#4.There is noticeble outliers in Popularity Column
#5.Genre column has Comma separated valuesand white spaces that needs to be handled and casted into category

df.head()

#1.Changing the Release_Date Column int date_time format from Object

df['Release_Date']=pd.to_datetime(df['Release_Date'])

print(df['Release_Date'].dtypes)

#Now Data type has changed to date_time format
#Now we will Change it to year Value only

df['Release_Date']=df['Release_Date'].dt.year
df['Release_Date'].dtypes

df.head()

# Release_Date has been updated as Year only and data typechaged to integer

#*******Dropping Column which we dont require*******#

Cols=['Overview', 'Original_Language', 'Poster_Url']
df.drop(Cols, axis=1,inplace=True)

df.columns

df.head(6)

#All 3 columns has been dropped from original data and Now dataframe has only 6 important column

#****Categorised Popularity****#
#Four labels can be there
#Popular, average, Below average, Not Popular

df['Vote_Average'].value_counts()

def Categorised_Col(df,Col, labels):

  edges=[df[Col].describe()['min'],
         df[Col].describe()['25%'],
         df[Col].describe()['50%'],
         df[Col].describe()['75%'],
         df[Col].describe()['max']]
  df[Col]=pd.cut(df[Col], edges, labels=labels, duplicates='drop')
  return df

Labels=['Not_Popular','Below_Average','Average','Popular']
df=Categorised_Col(df,'Vote_Average',Labels)

df.head()

df.dropna(inplace=True)

df.isna().sum()

df.head()

"""We wiil split Genre into a list"""

df['Genre']=df['Genre'].str.split(', ' )
df=df.explode('Genre').reset_index(drop=True)

df.head()

"""Casting Column into Category"""

df['Genre']=df['Genre'].astype('category')
df['Genre'].dtypes

df.head()

df.info()

"""**Now Data Preprocessing has been done**

**Data Visualization**
"""

sns.set_style('whitegrid')

"""**What is the most frequent Genre of Movies Released on Netflix?**

"""

df['Genre'].describe()

sns.catplot(y='Genre', data=df, kind='count',
            order=df['Genre'].value_counts().index,
            color='#4285f5')

plt.title('Genre column distribution')
plt.show()

"""**Which has the higest Votes in Vote Average Column?**"""

sns.catplot(y='Vote_Average', data=df, kind='count',
            order=df['Vote_Average'].value_counts().index,
            color='#4285f5')

plt.title('Votes distribution')
plt.show()



"""**What Movie got the Highest Popularity and what is its Genre?**






"""

df[df['Popularity']==df['Popularity'].max()]

"""**What Movie got the Lowest Popularity and what is its Genre?**


"""

df[df['Popularity']==df['Popularity'].min()]



"""**Which year has most movies filmed?**"""

df['Release_Date'].hist()
plt.title('Release dateColumn Distribution')
plt.show()

"""Conclusion
Q1: What is the most frequent genre in the dataset?
Drama genre is the most frequent genre in our dataset and has appeared more than 14% of the times among 19 other genres.

Q2: What genres has highest votes?
we have 25.5% of our dataset with popular vote (6520 rows). Drama again gets the highest popularity among fans by being having more than 18 popularities.

Q3: What movie got the highest popularity? what's its genre?
Spider-Man: No Way Home has the highest popularity rate in our dataset and it has genres of Action, Adventure and Sience Fiction.

Q4: What movie got the lowest popularity? what's its genre?
The united states, thread' has the highest lowest rate in our dataset and it has genres of music, drama, 'war', 'sci-fi' and history'.

Q5: Which Decade has the most filmmed movies?
year 2020 has the highest filming rate in our dataset.
"""



